name: Trigger curl on merge to master

on:
  push:
    branches:
      - testbranch

jobs:
  curl:
    runs-on: ubuntu-latest
    environment: production
    steps:

      - name: Execute curl command
        run: curl -X POST -H "X-Dvet-Token:DEPLOY_TOKEN" https://www.dvet.se/killerbean -f
