name: deploy

on:
  push:
    branches:
      - master

jobs:
  curl:
    runs-on: ubuntu-latest
    environment: Production
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Execute curl command
       run: |
          curl -X POST \
            -H "X-Dvet-Token: ${{ secrets.DEPLOY_TOKEN_MASTER }}" \
            https://www.dvet.se/killerbean -f
